services:
  postgres:
    image: postgres:17.0
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pg_data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.docker/volumes/postgres